[tool.poetry]
name = "linkshorten"
version = "0.1.0"
description = ""
authors = ["Shub Raj Lama <hello@shubraj.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
